alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    environment: production
rule_files:
- rules/*.yml
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: flask_app
  metrics_path: /metrics
  static_configs:
  - targets:
    - localhost:5000
- job_name: node_exporter
  static_configs:
  - targets:
    - localhost:9100
- job_name: nginx
  static_configs:
  - targets:
    - localhost:9113
- job_name: grafana
  static_configs:
  - targets:
    - localhost:3000
- job_name: redis
  static_configs:
  - targets:
    - localhost:9121
- job_name: stream_ad_exchange
  static_configs:
  - targets:
    - localhost:5000
  metrics_path: /app-metrics
  scrape_interval: 10s
  scheme: http
  relabel_configs:
    - source_labels: [__address__]
      target_label: app
      replacement: stream_ad_exchange
- job_name: vpn_metrics
  static_configs:
  - targets:
    - localhost:9176
  metrics_path: /metrics
  scrape_interval: 30s
- job_name: api_endpoints
  metrics_path: /metrics
  static_configs:
  - targets:
    - localhost:5000
  relabel_configs:
    - source_labels: [__address__]
      target_label: service
      replacement: api
- job_name: process
  static_configs:
  - targets:
    - localhost:9256
  scrape_interval: 30s
- job_name: network
  static_configs:
  - targets:
    - localhost:9100
  metrics_path: /metrics
  params:
    collect[]:
      - netstat
      - netdev
- job_name: log_metrics
  static_configs:
  - targets:
    - localhost:9198
  scrape_interval: 30s
