# API Configuration
MARKETSTACK_API_KEY = 'YOUR_MARKETSTACK_API_KEY'
COINLAYER_API_KEY = 'YOUR_COINLAYER_API_KEY'
ALPHA_VANTAGE_API_KEY = 'YOUR_ALPHA_VANTAGE_API_KEY'
POLYGON_API_KEY = 'YOUR_POLYGON_API_KEY'

# API Endpoints
MARKETSTACK_ENDPOINT = 'http://api.marketstack.com/v1'
COINLAYER_ENDPOINT = 'http://api.coinlayer.com'
ALPHA_VANTAGE_ENDPOINT = 'https://www.alphavantage.co/query'
POLYGON_ENDPOINT = 'https://api.polygon.io/v2' 